
module.exports = {


rebecca: {
    avatar: "http://www.myiconfinder.com/uploads/iconsets/256-256-58063dcbb6764fcf4850dd7b8cb493cf-nurse.png",
    firstname: 'Rebecca',
    lastname: "Racicot",
    city: 'La Ciotat',
    message: "Salut tout le monde ! J’ai toujours voulu apprendre le <strong>piano</strong>. Y-a t’il une personne près de moi qui pourrait m’apprendre les bases ?",
    skills: ["basket", "danse", "cuisine asiatique", "poker"],
    description: "Danseuse Classique pro, passionnée. 27 ans, je recherche des personnes fiables pour m’initier à la musique.",
    location: {lat: 43.174049, lng: 5.604220},
    wallPosition: 1,
    like: 26,
    comments: 11,
    timeAgo: 1,
    category: ["music", "all"],
},
eric: {
    avatar: "https://cdn1.iconfinder.com/data/icons/business-avatar-vol-2/16/avatar_man_people_person_rockstar_profile_human-128.png",
    firstname: 'Eric',
    lastname: "Henrichon",
    city: 'Martigues',
    message: "Hey ! Tous les dimanches matin, je m’exerce au <strong>Taï Chi</strong> si des personnes veulent se joindre à moi vous êtes le bienvenue 😊",
    skills: ["kungfu", "taï chi", "maçonnerie", "chant", "peinture"],
    description: 'Marque : Eric(sson) | Modèle : LAHAYE family V.2 | Type de produit : Masculin | Lieu de fabrication : Made in Provence | Objets des pièces détachées : France, Corse, Tunisie | Certification CERFA : 100% Spartan',
    location: {lat: 43.596321, lng: 0.267214},
    wallPosition: 2,
    like: 10,
    comments: 8,
    timeAgo: 3,
    category: ["sport", "all"],
},
david: {
    avatar: "https://m.media-amazon.com/images/I/51JUJVr32aL._AA256_.jpg",
    firstname: 'David',
    lastname: "Duranseau",
    city: 'Estaque',
    message: "Qui est dispo pour m’apprendre à <strong>pêcher</strong> proprement ? Je ramènerais quelques bières en récompense ! 😁",
    skills: ["ukulélé", "photographie", "cuisine asiatique", "poker"],
    description: "32 ans, cherche à vivre de nouvelles expériences et apprendre de nouvelles choses durant mon temps libre.",
    location: {lat: 43.366719, lng: 5.316073},
    wallPosition: 3,
    like: 127,
    comments: 86,
    timeAgo: 8,
    category: ["fish", "all"],

},
john: {
    avatar: "https://cdn1.vectorstock.com/i/1000x1000/31/95/user-sign-icon-person-symbol-human-avatar-vector-12693195.jpg",
    firstname: 'John',
    lastname: "Doe",
    city: 'Marseille',
    message: "Bonjour à tous ! Je suis développeur passionné et expérimenté. Si le <strong>code</strong> est un domaine qui vous intéresse contactez moi et je me ferais un plaisir de vous initier à l’art du <strong>code</strong> !",
    skills: ["web", "design", "ui", "interface", "graphisme", "developpement", "SEO"],
    description: "Salut ! Mon nom est John, je suis un geek créatif, venu tout droit de Marseille. J'adore concevoir des applications web et mobile aussi visuellement belles que techniques, mais aussi le jogging et la lecture.",
    location: {lat: 43.296482, lng: 5.369780},
    wallPosition: 4,
    like: 23,
    comments: 2,
    timeAgo: 11,
    category: ["code", "all"],
},
julie: {
    avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7S0r-4h1wUG98xk1QUpcfkYyxba-OInHzI6QVzU6D5JViwYUDHQ",
    firstname: 'Julie',
    lastname: "Quill",
    city: 'Toulon',
    message: "Bonsoir y aurait-il un pure geek dans les alentours qui pourrait m’aider à élever mon niveau sur <strong>Fornite</strong> ?",
    skills: ["gaming", "jogging", "cluedo", "basket"],
    description: "Je s'appelle Groot",
    location: {lat: 43.125191, lng: 5.931040},
    wallPosition: 5,
    like: 98,
    comments: 67,
    timeAgo: 18,
    category: ["game", "all"]

},
aurelie: {
    avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMOZsQwqJXSteMRxlyKJUTctdSutWiovjVS_KeemH_wQj2dAKvzg",
    firstname: 'Aurelie',
    lastname: "Parizeau",
    city: 'Marseille',
    message: "Bonjour, j’aimerais apprendre à <strong>cuisiner</strong> de vrais <strong>plats orientaux</strong> avec un savoir faire traditionnel et non pas venu des livres de cuisine. Je préfère apprendre directement d’une personne ayant déjà beaucoup d’expériences dans le domaine. Veuillez me contacter pour que l’on puisse échanger ensemble 😉",
    description: "Styliste Marié, mère de 2 enfants / “Une vie à écrire” | Contact pro : Aurélie@contact.com",
    skills: ["web", "design", "graphisme", "developpement", ],
    location: {lat: 43.296483, lng: 5.369783},
    wallPosition: 6,
    like: 290,
    comments: 98,
    timeAgo: 23,
    category: ["food", "all"],

}
}